### ISSUE TITLE
Create and Implement REQ-completion

### ISSUE THREAD

**Issue by sanmai-NL** [vitiral/artifact#178]
Marking:
```
\\ #SPC-compressed_archive
...
```
Leads to a 50 % complete item in `art ls` given a single child:

```
|--|  50%   0% | SPC-compressed_archive                    | SPC-compressed_archive-member_relevancy
|--|   0%   0% | SPC-compressed_archive-member_relevancy   
```

If the parent is marked, it could be considered fully complete (forcefully), or still 0 % complete since the children should be marked complete instead.

**Comment by vitiral** [comment]
**Related**: the spec in [SPC-artifact](https://vitiral.github.io/artifact/#artifacts/spc-artifact) needs to be updated to reflect the new design. Somehow I forgot to do that.

The original logic was to have `#SPC-foo` mark anything as 100% done all the time. That was annoying, because you often want to link to parent items in code, as well as their children.

In the end, I settled on either the `done=` field or a link in code being the equivalent of a "done child". Note that if you *do mark the children as done* (either in code or with `done=`), then you don't need to mark the parent as done -- which is the behavior you want in the end.

This gives you an idea that:
- The parent is implemented somewhere in code
- Its children are not

This leads to being 50% done for a single child parent (which in my experience is unusual), to 33% done with two children, 25% with three children, etc -- and is a reasonably good description of the completion status of the item.

I would love to know more about your thinking. We can put these thoughts into the new SPC/REQ, which probably needs to be written to elaborate this more.

**Comment by sanmai-NL** [comment]
I can see how marking the parent as partially complete could be handier than other solutions. But it is more surprising and inconsistent too. What I did not get from your reply.. why is it not okay to mark the parent as 0 % done when all its children are 0 % done?

**Comment by vitiral** [comment]
So I'm thinking one solution for this might be to just *ignore* the code-link/done-field if the item has any children. That would *allow you to link* but would also make it simply equal to the average of it's children.

**Comment by vitiral** [comment]
Please comment on #184 and tell me what you think!

**Comment by vitiral** [comment]
So I've decided to not pursue this design. The primary reason is that it doesn't account for use cases where some of the logic is implemented and linked in the parent artifact. This will be especially important in reference to #186.

I am working on formalzing the logic and requirement using graphiz. Hopefully it should at least be easier to understand.

One of the things I am least concerned about with this library is having the %done/%tested reflect any kind of "real percent" -- all it does is give a flag that something is almost done or not very done at all (or has no test definition, etc).

Thanks for the issue and the discussion, but I think the behavior here should be unchanged.
