### ISSUE TITLE
Use labels (connected graph) instead of tree for items

### ISSUE THREAD

**Issue by sanmai-NL** [vitiral/artifact#183]
I’ll start out this issue philosophically, so let’s discuss a bit.

Suppose a requirement has both significant security and performance reasons. Currently with Artifact it seems you would have to file them as REQ-security-... or REQ-performance-.... This isn't really optimal because you cannot immediately track down all open security or performance issues this way. 

Artifact could create unique value here by providing a means to relate ‘items of a Kanban-board like nature’ (i.e. issues, see e.g. [GitLab](https://docs.gitlab.com/ee/user/project/issue_board.html)), organized with tags, to the actual source code. This representation of the requirements, implementations and tests would no longer necessarily be a tree though.

I have an alternative proposal as well. References to [Pijul patches](https://pijul.org/manual/why_pijul.html) could be a better way to track progress than annotations in comments, how Artifact currently works. ‘Progress’ could be defined to mean anything from implementing and testing formal requirements to resolved issues on a Kanban board. Why is it better? Since with Artifact, a line asserting that the following(?) code implements a certain requirement only remains connected to the actual code through discipline of the programmer. If the code is changed meaningfully so that the requirement or even specification is no longer met, it’ll be hard to catch that. If you miss it as manager, then the Artifact overview won't be accurate anymore. With Pijul patches, it is always possible to detect how source code that met a requirement earlier is affected in the event another patch is merged later.

**Comment by vitiral** [comment]
Sorry I haven't gotten to this. I am on haitus from this project for a little while while I help with the rust-impl period. I'm collecting some thoughts on what I want to do for 2.0 and will consider this then.

**Comment by vitiral** [comment]
I'm not sure I follow. Let me make sure I understand your proposal. As I see it there are two of them:

## Feature1: add the ability to add "tags"
This is something I would use #107 for. One of the design requirements of artifact is that it is very slow to add features.

## Feature 2: use pijul to track progress
I'm a little confused about the implementation here. I'm not sure why Pijul could provide any kind of automated way of detecting that a requirement changed (other than the way other version control systems already do). Also, I am unwilling to tie artifact to any *particular* vcs system

Related: I have another design I've been throwing around that I've been thinking could help address this. It would allow you to define "mini specifications" *inside* the text block of SPC or TST types that can link to source code. So you could do something like this:

```
[SPC-foo]
text = '''
This has multiple parts of implementation:
- [[.input]]: take the input
- [[.process]]: process the input
- [[.log]] log the result
'''
```

Each of these "sub-parts" could then be linked in code using `#SPC-foo.input`, `#SPC-foo.process`, etc. Since the `.` character is currently illegal, there is no possibility of overlap.

The sub-parts would then be used for also calculating the completeness of the item.

**Comment by vitiral** [comment]
I opened #186 to track the second feature I proposed.

**Comment by vitiral** [comment]
Since there has not been commentary on this for about two weeks I am closing. Feel free to reopen if you have additional comments.
