### ISSUE TITLE
[post 2.0] svgbob integration

### ISSUE THREAD

**Issue by matthiasbeyer** [vitiral/artifact#226]
Would be awesome and maybe a nice idea to integrate [svgbobrus](https://github.com/ivanceras/svgbobrus/) for rendering graphs.

Maybe not for the next release (as this is already packed with new ideas and todos) but for the release after the next one...

**Comment by vitiral** [comment]
We would need to compile it as javascript and do the rendering client side. I'm not insterested in having server side rendering for this application.

Even if we did have that, I'm not 100% convinced what te benefits are vs graphviz. I suppose it gives you even *more* control. You can also do things like write circuit diagrams, so that could be useful to some people.

One of the issues is that if I *did* integrate this, I would want the text editor to be *significantly* better, as editing these by hand looks like a complete pain.

Just a couple of blockers off the top of my head.

**Comment by matthiasbeyer** [comment]
I like svgbob because it is WYSIWYG (kinda) ... graphviz is not. Just to note that! Awesome that you consider it!

**Comment by vitiral** [comment]
I think svgbob integration is unlikely in the forseeable future. Closing, but thanks for the suggestion!

**Comment by bbigras** [comment]
Server side support for many tools like svgbob, plantuml, GraphViz, mermaid... would be a killer feature. I would switch design documentation tool for that.
