### ISSUE TITLE
text field is truncated during export

### ISSUE THREAD

**Issue by Xisto1979** [vitiral/artifact#234]
it is not possible not to cut off the text field by ls command and output it completely also on export

**Comment by vitiral** [comment]
Can you describe the behavior you are experiencing more? What is truncated? Is it just white-space (this is by design) or is actual text truncated?

**Comment by Xisto1979** [comment]
If you call "art ls -A", the text is truncated from the "Text" field.

**Comment by vitiral** [comment]
@Xisto1979 hey, this is actually working as intended. The idea is that you don't want everything when listing because it would be messy in the table format.

using `-l` or `--long` will give you the whole text but it will be truncated in the table.

What is the use case that you need the full text in the table?
