### ISSUE TITLE
TT: Test Tracking Tool

### ISSUE THREAD

**Issue by vitiral** [vitiral/artifact#58]
This issue is for tracking the development of the test tracking tool. Please link external documents and have general conversation in this thread.

This is in the design docs as:

http://vitiral.github.io/artifact/#artifacts/REQ-TRACKER

**Comment by rubdos** [comment]
I feel like this feature could be an external tool that uses artifact (as a library, or using an intermediate protocol) rather that putting these things inside artifact, as currently `art` is used completely stateless, and adding a SQL database would require to "track state".

**Comment by vitiral** [comment]
I agree, eventually it will be broken out into its own crate. For now it is behind a feature flag and not compiled for the release builds, which is adequate. 

I want the core libraries to be stabilized before I start breaking up into crates. My first pass at that happened a week ago, but it will probably be several months before everything is stable enough.

**Comment by packapotatoes** [comment]
I can not for the life of my get Diesel to install...
I've done everything I can possibly find and still get errors while compiling diesel_cli

```
error: linking with 'cc' failed: exit code: 1
```
Then a huge wall of text that might be my path, then
```
/usr/bin/ld: cannot find -lpq
/usr/bin/ls: cannot find -lmysqlclient
```

I have postgresql installed (two versions at this point, possibly in multiple places) and sqlite3. 
From what I can tell, the linker can't find the installation or specific files from the installation. 

Does anyone have suggestions on how to fix this, or where I should go for more help? Should I contact the Diesel team, or just post on stackexchange?

**Comment by vitiral** [comment]
Please contact the diesel team by opening an issue on github

**Comment by packapotatoes** [comment]
For anyone else with this problem:
I used mann-ed's answer [here](https://github.com/diesel-rs/diesel/issues/321#issuecomment-218332202)

I started with `sudo updatedb && sudo locate libpq` which gave a few results. I found `usr/lib/x86_64-linux-gnu/libpq.so.5` which was quite similar to the path in the link ( `/usr/pgsql-9.3/lib/libpq.so.5` ).

I then created a symlink to /usr/lib/libpq.so (where diesel expects this library) using 
'sudo ln -s /usr/lib/x86_64-linux-gnu/libpq.so.5 /usr/lib/libpq.so`

Then I was able to successfully install diesel with `cargo install diesel_cli --force --no-default-features --features 'postgres'

(I used `--force` because I accidentally installed diesel without the postgres feature, and needed `--force` to overwrite the install. It shouldn't be necessary for a clean install)

**Comment by vitiral** [comment]
I thought you guys are using sqlite?

**Comment by packapotatoes** [comment]
ARgh, is that where we landed? I totally forgot, I guess it's back to the drawing board. I'm just about to send an email to my group trying to clarify a few things and set up better communication. I'll also ask where they stand with postgresql and sqlite. 

My end goal is to install with support for both sqlite and postgresql so that it won't be an issue.

**Comment by vitiral** [comment]
Sqlite is just for the mvp, so that would be a good idea

- sent from my Android

**Comment by packapotatoes** [comment]
After installing mysql and `libmysqlclient-dev` and `libmysqlclient20` from [here](https://dev.mysql.com/doc/mysql-apt-repo-quick-guide/en/#repo-qg-apt-available), I successfully installed Diesel with default settings. I don't know if libmysqlclient20 was needed, but it might be.

**Comment by vitiral** [comment]
closing all test tracker bugs for now. Need to think how it should be designed and whether it should actually exist in artifact propper or as a separate app.
